from src.commands.naks_commands.commands import ParseNaksWeldersCommand, ParseNaksACSTCommand
from src.commands.file_commands.commands import SortWelderFilesCommand
from src.commands.db_commands.commands import AddWelderNDTsCommand, AddWeldersCommand, DownloadWelderNDTsCommand, UpdateWeldersCommand
from src.commands.registry_commands.commands import UpdateWelderNDTRegistryCommand
