from src.repositories.welder_repository import WelderRepository
from src.repositories.welder_certification_repository import WelderCertificationRepository
from src.repositories.welder_ndt_repository import WelderNDTRepository
from src.repositories.user_repository import UserRepository